### PR TITLE
(BA-871) setup monorepo

### PR DESCRIPTION
**Pull request by anicioalexandre**
- migrate the `baseapp-nextjs-core` into the `baseapp-frontend` monorepo
- implement versioning + npm release pipeline

### CODE REVIEW

**Comment by rafaelhdr** [comment]
That is amazing :). I loved it. But we will need a follow-up for baseapp-mui, right? (to use the packages from here)

Also, tiny addition. Could we have a `.nvmrc` here? Just to pin and follow the flow before the `yarn install`?

**Review by rafaelhdr — COMMENTED** [review]
And this is our first open-source project. I think we need a license for it (but not sure which one tho)

**Comment by anicioalexandre** [comment]
> And this is our first open-source project. I think we need a license for it (but not sure which one tho)

I used the MIT one, also not sure which one is the best option. Maybe @whatSocks have an idea?

**Comment by Janekk** [comment]
Nice work, a lot of things updated! @anicioalexandre curious, what is `turbo` doing for us? Is it building across all the packages?

**Comment by Janekk** [comment]
@anicioalexandre  when I run `yarn run dev` I'm getting an infinite of these:

```
docs:dev: Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch
```
@Janekk  try to run `yarn clean` and then `yarn install ` again, you could increase the nummber of watchers on you machine also, I think that happens when we run multiple projects

**Comment by Janekk** [comment]
@anicioalexandre so `apps/docs` is meant to be a little own nextjs project for App Documentation?

**Comment by anicioalexandre** [comment]
> Nice work, a lot of things updated! @anicioalexandre curious, what is `turbo` doing for us? Is it building across all the packages?

it helps us to build, manage the dependencies and run each package/app. Also speed up a lot the development, we could also cache the builds for even faster builds. It's a simple tool, very easy to configure, but very powerful at the same time

**Comment by anicioalexandre** [comment]
> @anicioalexandre so `apps/docs` is meant to be a little own nextjs project for App Documentation?

@Janekk yes, we could thes new packages features in that app, maybe add some documentation on a page, to help the developper understand how it should be used. In the future we could have a storybook app to display component from a design-system for instance as well

**Review by nossila — APPROVED** [review]

**Pull request merged**
